### PR TITLE
Preflop hj, co, and sb action

### PR DESCRIPTION
**Pull request by anthonycasarta**
Added preflop hj, co, and sb actions with corresponding tests.

### CODE REVIEW

**Review by MarcoCasar — COMMENTED** [review]
The SB and BTN positions return an invalid position error when chosen

**Review by MarcoCasar — COMMENTED** [review]
When the position SB is chosen with the hand AsKd, the raise and fold options both return an error that the choice is incorrect

**Comment by anthonycasarta** [comment]
I updated the valid actions for the user.

**Review by MarcoCasar — APPROVED** [review]
Works

**Pull request merged**
